arch: UNet
augment_inference: false
batch_size: 24
boundary_loss_weight: 0.1
boundaryloss: null
encoder_name: resnet50
img_size: 256
in_channels: 1
learning_rate: 0.0001
len_train_loader: 50
loss_kwargs: null
out_classes: 1
threshold: 0.4
use_boundary_loss: false
